"""
ml/simulate.py
Dynamic multi-hop transaction simulation engine.
Simulates new incoming evidence (subsequent mule transfer) for an active case
and re-computes probabilistic location rankings in real-time WITHOUT retraining the model.
"""

from typing import Dict, Any, List, Optional
import pandas as pd
import numpy as np

from ml.predict import get_inference_resources, predict_locations


def simulate_transaction(
    case_id: str,
    new_tx_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Simulates the arrival of a new downstream mule transaction:
    1. Obtains current 'Before' predictions.
    2. Injects the new transaction into the active case's chain.
    3. Re-computes topological graph metrics, velocities, and spatial distances.
    4. Evaluates the ML model to produce 'After' rankings.
    5. Returns genuine before/after comparative shifts generated by the model.
    """
    model, feature_cols, data = get_inference_resources()
    all_tx = data["transactions"].copy()

    # 1. Baseline inference before new evidence
    before_result = predict_locations(case_id)

    # 2. Format and inject new transaction
    tx_time = pd.to_datetime(new_tx_data["timestamp"])
    new_row = {
        "transaction_id": new_tx_data.get("transaction_id", f"T_SIM_{len(all_tx)+1}"),
        "case_id": case_id,
        "sender_account": str(new_tx_data["sender_account"]),
        "receiver_account": str(new_tx_data["receiver_account"]),
        "amount": float(new_tx_data["amount"]),
        "timestamp": tx_time,
        "transaction_type": new_tx_data.get("transaction_type", "Transfer")
    }

    # If receiver account has a new region attribute, update account_lookup
    if "receiver_region" in new_tx_data:
        data["account_lookup"][str(new_tx_data["receiver_account"])] = {
            "case_id": case_id,
            "account_type": "Mule",
            "region": str(new_tx_data["receiver_region"]),
            "account_age_days": new_tx_data.get("receiver_age_days", 180)
        }

    updated_tx_df = pd.concat([all_tx, pd.DataFrame([new_row])], ignore_index=True)

    # 3. Re-run inference with the new evidence at the new cut-off time
    after_result = predict_locations(
        case_id=case_id,
        prediction_time=tx_time,
        custom_transactions_df=updated_tx_df
    )

    # 4. Calculate comparative shifts
    before_scores = {x["location_id"]: (x["rank"], x["score"], x["city"]) for x in before_result["all_ranked_locations"]}
    after_scores = {x["location_id"]: (x["rank"], x["score"], x["city"]) for x in after_result["all_ranked_locations"]}

    shifts = []
    for loc_id, (b_rank, b_score, city) in before_scores.items():
        a_rank, a_score, _ = after_scores[loc_id]
        rank_change = b_rank - a_rank  # positive = improved rank (e.g. 3 -> 1 is +2)
        score_change = round(a_score - b_score, 4)
        shifts.append({
            "location_id": loc_id,
            "city": city,
            "before_rank": b_rank,
            "after_rank": a_rank,
            "rank_change": rank_change,
            "before_score": b_score,
            "after_score": a_score,
            "score_change": score_change,
        })

    # Sort shifts by after_rank
    shifts.sort(key=lambda x: x["after_rank"])

    return {
        "case_id": case_id,
        "simulated_transaction": new_row,
        "before_prediction_time": before_result["prediction_time"],
        "after_prediction_time": after_result["prediction_time"],
        "before_time_window": before_result["estimated_cashout_time_window"],
        "after_time_window": after_result["estimated_cashout_time_window"],
        "before_top_3": before_result["top_3"],
        "after_top_3": after_result["top_3"],
        "top_shifts": shifts[:5],
        "disclaimer": before_result["disclaimer"]
    }


def demo_simulation():
    """Runs a demonstration of transaction simulation on an active case."""
    test_case = "C0001"
    print("=" * 80)
    print(f"DEMO: SIMULATING DYNAMIC MULE TRANSFER EVIDENCE FOR CASE {test_case}")
    print("=" * 80)

    # Case C0001 was cashed out in Bengaluru (L001) / previous mule in Chennai
    # Let's simulate a sudden rapid mule-to-mule hop towards Mumbai / Cluster G
    new_transfer = {
        "transaction_id": "T_SIM_001",
        "sender_account": "A0001_5",
        "receiver_account": "A0001_9_NEW",
        "receiver_region": "Mumbai",
        "amount": 25000,
        "timestamp": "2026-06-13 05:45:00",
        "transaction_type": "Transfer"
    }

    print(f"\n[Injecting New Evidence]:")
    print(f"  {new_transfer['sender_account']} -> {new_transfer['receiver_account']} (Region: {new_transfer['receiver_region']})")
    print(f"  Amount: INR {new_transfer['amount']} | Timestamp: {new_transfer['timestamp']}")

    sim_res = simulate_transaction(test_case, new_transfer)

    print("\n--- BEFORE NEW EVIDENCE ---")
    print(f"Prediction Time: {sim_res['before_prediction_time']} | Window: {sim_res['before_time_window']}")
    for loc in sim_res["before_top_3"]:
        print(f"  Rank {loc['rank']}: {loc['city']} ({loc['location_id']}) | Score: {loc['score']} | Risk: {loc['risk']}")

    print("\n--- AFTER NEW EVIDENCE (Dynamic ML Re-scoring without retraining) ---")
    print(f"Prediction Time: {sim_res['after_prediction_time']} | Window: {sim_res['after_time_window']}")
    for loc in sim_res["after_top_3"]:
        print(f"  Rank {loc['rank']}: {loc['city']} ({loc['location_id']}) | Score: {loc['score']} | Risk: {loc['risk']}")

    print("\n--- NOTABLE LOCATION SHIFTS ---")
    for s in sim_res["top_shifts"][:3]:
        delta_str = f"+{s['score_change']}" if s['score_change'] >= 0 else f"{s['score_change']}"
        rank_arrow = f"{s['before_rank']} -> {s['after_rank']}"
        print(f"  {s['city']} ({s['location_id']}): Rank {rank_arrow} | Score: {s['before_score']} -> {s['after_score']} ({delta_str})")



if __name__ == "__main__":
    demo_simulation()
